### ISSUE TITLE
Разобраться с gitignore

### ISSUE THREAD

**Issue by redboo** [redboo/knowledge#5]
Научиться использовать .gitignore.
Результатом будет считаться создание файла в корневой директории.

**Comment by Dukuu-Wild** [comment]
так, тогда мой сценарий:
Я отредактировал один файл, а в коммит добавились 3, 
два из них были какими-то настройками обсидиана и ещё чего-то с линуксом. 
Каждый по отдельности  я добавил в игнор.
Почему по отдельности: потому, что если спрячу всю папку, то могу зацепить что-то полезное.

А ожидаем что?

**Comment by redboo** [comment]
Добавил [страницу](https://github.com/redboo/knowledge/blob/master/github/gitignore.md) о gitignore. Зачем и как использовать.

**Comment by redboo** [comment]
Создан файл .gitignore и добавлена страница документации.
